spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

  datasource:
    url: jdbc:mysql://${DB_MYSQL_HOST:127.0.0.1}:${DB_MYSQL_PORT:3306}/beyhub_pages?characterEncoding=utf8&useSSL=false&autoReconnect=true&useUnicode=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_MYSQL_USERNAME:root}
    password: ${DB_MYSQL_PASSWORD:Beyhub@123}
    hikari:
      connection-init-sql: "SET NAMES 'utf8mb4'"